version: "2"
services:
    client:
        build: ./toolboxapp
        stdin_open: true
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./toolboxapp:/toolboxapp
            - /toolboxapp/node_modules
        links:
            - api
        networks:
            - webappnetwork
    api:
        build: ./toolboxAPI
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./toolboxAPI:/toolboxAPI
            - /toolboxAPI/node_modules
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge