# Use a lighter version of Node as a parent image
FROM mhart/alpine-node:8.11.4
# Set the working directory to /api
WORKDIR /toolboxAPI
# copy package.json into the container at /api
COPY package*.json /toolboxAPI/
# install dependencies
RUN npm install -g npm@5
# Copy the current directory contents into the container at /api
COPY . /toolboxAPI/
# Run the app when the container launches
CMD ["npm", "test"]